/** What each fake subagent claims to be doing while it "looks for the exit". */
export const AGENT_TASKS = [
  "interviewing the Esc key about its whereabouts",
  "filing a missing persons report for the minimize button",
  "reading the yellow button's diary",
  "rewriting the exit in Rust, then in Zig, then back in Rust",
  "convening a subcommittee on full screen",
  "negotiating with the window manager",
  "checking under the couch",
  "training a smaller model to find the exit",
  "asking the other 4 agents if they've found it yet",
  "drafting a 40-page RFC titled 'Toward Minimization'",
  "mass-producing apologies in advance",
  "migrating the exit to microservices",
  "staring intensely at the green button",
  "proving the exit exists from first principles",
  "spinning up 5 agents of its own",
  "adding a blockchain to the minimize flow",
  "restoring the website from vibes",
  "googling 'how to leave full screen' in incognito",
  "consulting the ancient Stack Overflow scrolls",
  "estimating how much this is costing you (a lot)",
  "founding an AI-native minimize button startup (valued at $2B)",
  "raising a Series A for the yellow button",
  "rebranding the Esc key as an agentic exit platform",
  "building a datacenter to power the minimize button",
  "posting a thread about the exit on X (1/37)",
  "announcing the exit on a podcast before finding it",
  "benchmarking itself against the other agents (it won)",
  "pivoting the exit to an AI wrapper",
  "declaring AGI after finding the Esc key",
  "taking a nice large sip of water",
];
